name: Run Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install package dependencies
        run: npm i
      - name: Install test dependencies
        working-directory: ./test
        run: npm i
      - name: Install playwright browsers
        working-directory: ./test
        run: npx playwright install --with-deps
      - name: Test with Playwright
        working-directory: ./test
        run: npm run test
